# see docs/python-linting.md for more details
repos:
    # python import sorting - will amend files
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.0.9
      hooks:
          - id: isort

    # python code formatting - will amend files
    - repo: https://github.com/ambv/black
      rev: 20.8b1
      hooks:
          - id: black
            language_version: python3.7

    # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
            additional_dependencies: ["flake8-docstrings", "flake8-bandit"]
            exclude: tests|migrations

    # python static type checking
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
          - id: mypy
            args:
                - --ignore-missing-imports
                # means we only get error on the current file
                - --follow-imports=silent
