# Generated by Django 3.2.6 on 2021-08-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0004_leadsource_gclid"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadsource",
            name="aclk",
            field=models.CharField(
                blank=True,
                help_text="Identifies a Microsoft Ad click (bing), is used for ad tracking.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="leadsource",
            name="fbclid",
            field=models.CharField(
                blank=True,
                help_text="Identifies a Facebook Ad click, is used for ad tracking.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="leadsource",
            name="msclkid",
            field=models.CharField(
                blank=True,
                help_text="Identifies a Microsoft Ad click (MS ad network), is used for ad tracking.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="leadsource",
            name="twclid",
            field=models.CharField(
                blank=True,
                help_text="Identifies a Twitter Ad click, is used for ad tracking.",
                max_length=255,
            ),
        ),
    ]
