# Generated by Django 3.2.11 on 2022-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0005_auto_20210809_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadsource",
            name="custom_tags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dict of custom tag:value pairs as defined by the UTM_TRACKER_CUSTOM_TAGS setting.",
                null=True,
            ),
        ),
    ]
