# Generated by Django 3.2.12 on 2022-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0006_leadsource_custom_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsource",
            name="content",
            field=models.CharField(
                blank=True,
                help_text="utm_content: Identifies what specifically was clicked to bring the user to the site, such as a banner ad or a text link.",
                max_length=100,
            ),
        ),
    ]
