# Generated by Django 4.0.5 on 2023-02-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utm_tracker", "0008_increase_charfield_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsource",
            name="timestamp",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the event occurred (if known).",
                null=True,
            ),
        ),
    ]
