name: Python / Django

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [fmt,lint,mypy]
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install and run tox
        run: |
          pip install tox
          tox

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8","3.10"]
        django: [32,40,41,42,50,main]
        exclude:
          - python: "3.8"
            django: "50"
          - python: "3.8"
            django: "main"

    env:
      TOXENV: py${{ matrix.python }}-django${{ matrix.django }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install and run tox
        run: |
          pip install tox
          tox
